# Generated by Django 2.2.7 on 2019-11-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('phone1', models.CharField(blank=True, max_length=11, null=True)),
                ('phone2', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('rental', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order_date', models.DateField(verbose_name='Job order date')),
                ('start_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Job start date and time')),
                ('completion_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Job completions date')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Property')),
            ],
        ),
    ]
